package com.priv.cote.main;

import com.priv.cote.component.TwoDimentionArray.ColoredPaper;
import com.priv.cote.component.TwoDimentionArray.MatrixAddition;
import com.priv.cote.component.TwoDimentionArray.MaxValue;
import com.priv.cote.component.TwoDimentionArray.VerticalRead;
import com.priv.cote.component.deeping1.*;
import com.priv.cote.component.divisorMultipleDecimal.MultipleDivisor;
import com.priv.cote.component.mathmatics.*;
import com.priv.cote.component.string.*;

public class Main {
    public static void main(String[] args) throws Exception {
//        new ADivisionB().division();
//        new AFourBasicOperationsB().fourBasicOperations();
//        new AQuestionMarkB().plusQuestionMark();
//        new A1998To2541B().a1998To2541B();
//        new AEqualsRemainB().equalsRemain();
//        new AMultiplicationProcessB().multiplicationProcess();
//        new APlusTripleB().plusTriple();
//        new PrintCat().printCat();
//        new PrintDog().printDog();
//        new ACompareB().print();
//        new TestScore().print();
//        new LeafYear().print();
//        new Quadrant().print();
//        new AlarmClock().print();
//        new OvenClock().print();
//        new Dice().print();
//        new NineNineDan().print();
//        new AAddBLoof().print();
//        new OneToN().print();
//        new Receipt().print();
//        new CodingIsPhysical().print();
//        new FastAPlusB().print();
//        new BeautifulAPlusB().print();
//        new BeautifulAPlusB2().print();
//        new Stars1().print();
//        new Stars2().print();
//        new AAddBLoofLast0().print();
//        new AAddBLoofNoLast().print();
//        new CountNumber().print();
//        new SmallThanX().print();
//        new MinMax().print();
//        new WhereIsMax().print();
//        new PlaceBall().print();
//        new ChangeBall().print();
//        new Homework().print();
//        new FortyTwo().print();
//        new ReverseBasket().print();
//        new TestAvgFake().print();
//        new StringAndString().print();
//        new StringLength().print();
//        new StringString().print();
//        new StringToAscii().print();
//        new TotalOfString().print();
//        new FindAlphabet().print();
//        new StringLoop().print();
//        new CountWords().print();
//        new Constant().print();
//        new PrintSame().print();
//        new Dial().print();
//        new Sprout().print();
//        new KingQueenLook().print();
//        new StarDrawing().print();
//        new Palindrome().print();
//        new CroatiaWords().print();
//        new GroupWordChecker().print();
//      new YourScoreIs().print();
//      new MatrixAddition().print();
//      new MaxValue().print();
//      new VerticalRead().print();
//      new ColoredPaper().print();
//      new BaseConversion().print();
//      new BaseConversion2().print();
//      new CenterMoveAlgorithm().print();
//      new BeeHouse().print();
//      new Fraction().print();
//      new Snail().print();
      new MultipleDivisor().print();
    }
}
